# Generated by Django 3.0.3 on 2020-02-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_auto_20200223_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentalResult',
            new_name='Example',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='experience',
            new_name='example',
        ),
    ]
